# Generated by Django 5.0.1 on 2024-02-11 09:06

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_alter_tagpost_options_remove_women_tags_women_tag_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='women',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='women',
            old_name='tag',
            new_name='tags',
        ),
    ]
