# Generated by Django 5.0.1 on 2024-02-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_husband_women_husband'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='husband',
            options={'verbose_name': 'Муж', 'verbose_name_plural': 'Мужья'},
        ),
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Опубликовано'), (False, 'Черновик')], default=0, verbose_name='Опубликовано'),
        ),
    ]
